version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: chaybot
      POSTGRES_USER: chayuser
      POSTGRES_PASSWORD: chaypass
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://chayuser:chaypass@db:5432/chaybot
    command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh db 5432 -- pip install -r requirements.txt && alembic upgrade head"

  bot:
    build: .
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgresql+asyncpg://chayuser:chaypass@db:5432/chaybot
    command: python -m bot.bot
    restart: always
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pgdata:
