version: '3.9'

services:
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: chaybot
      POSTGRES_USER: chayuser
      POSTGRES_PASSWORD: chaypass
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+asyncpg://chayuser:chaypass@db:5432/chaybot
      REDIS_URL: redis://redis:6379/0
    command: python -m bot.bot
    restart: always
    volumes:
      - .:/app
    working_dir: /app

volumes:
  pgdata:
  redisdata: