"""Add second photo

Revision ID: 1fcfa131ef2b
Revises: 790674436893
Create Date: 2025-08-21 16:48:54.435684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcfa131ef2b'
down_revision: Union[str, None] = '790674436893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('ingredients_photo_url', sa.String(), nullable=True))
    op.add_column('dishes', sa.Column('ready_photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'ready_photo_url')
    op.drop_column('dishes', 'ingredients_photo_url')
    # ### end Alembic commands ###
